-- MOVIE
INSERT INTO MOVIE (ID, TITLE, RELEASE_DATE)
VALUES (MOVIE_SEQ.NEXTVAL, 'Avengers: Endgame', TO_DATE('2019-04-26', 'YYYY-MM-DD'));

INSERT INTO MOVIE (ID, TITLE, RELEASE_DATE)
VALUES (MOVIE_SEQ.NEXTVAL, 'John Wick 3: Chapter 3 - Parabellum', TO_DATE('2019-05-17', 'YYYY-MM-DD'));

INSERT INTO MOVIE (ID, TITLE, RELEASE_DATE)
VALUES (MOVIE_SEQ.NEXTVAL, 'Aladdin', TO_DATE('2019-05-24', 'YYYY-MM-DD'));

-- MOVIE_GENRE
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'), 'ACTION');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'), 'ADVENTURE');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'), 'SCI_FI');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'), 'ACTION');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'), 'CRIME');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'), 'THRILLER');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Aladdin'), 'ADVENTURE');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Aladdin'), 'COMEDY');

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE)
VALUES ((SELECT ID FROM MOVIE WHERE TITLE = 'Aladdin'), 'FAMILY');

-- HALL
INSERT INTO HALL (ID, NAME, ROWS_COUNT, SEATS_COUNT) VALUES (HALL_SEQ.NEXTVAL, 'Hall 1', 20, 30);
INSERT INTO HALL (ID, NAME, ROWS_COUNT, SEATS_COUNT) VALUES (HALL_SEQ.NEXTVAL, 'Hall 2', 10, 20);
INSERT INTO HALL (ID, NAME, ROWS_COUNT, SEATS_COUNT) VALUES (HALL_SEQ.NEXTVAL, 'Hall 3', 5, 15);

-- MOVIE_SESSION
INSERT INTO MOVIE_SESSION (ID, MOVIE_ID, HALL_ID, START_TIME, PRICE)
VALUES (MOVIE_SESSION_SEQ.NEXTVAL,
        (SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'),
        (SELECT ID FROM HALL WHERE NAME = 'Hall 1'),
        TO_DATE('2019-05-19 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        150);

INSERT INTO MOVIE_SESSION (ID, MOVIE_ID, HALL_ID, START_TIME, PRICE)
VALUES (MOVIE_SESSION_SEQ.NEXTVAL,
        (SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'),
        (SELECT ID FROM HALL WHERE NAME = 'Hall 1'),
        TO_DATE('2019-05-19 20:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        170);

INSERT INTO MOVIE_SESSION (ID, MOVIE_ID, HALL_ID, START_TIME, PRICE)
VALUES (MOVIE_SESSION_SEQ.NEXTVAL,
        (SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'),
        (SELECT ID FROM HALL WHERE NAME = 'Hall 2'),
        TO_DATE('2019-05-19 21:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        120);

-- APP_USER
INSERT INTO APP_USER (ID, USERNAME, PASSWORD, FULL_NAME) VALUES (APP_USER_SEQ.NEXTVAL, 'bmelany', 'bm123', 'Braden Melany');
INSERT INTO APP_USER (ID, USERNAME, PASSWORD, FULL_NAME) VALUES (APP_USER_SEQ.NEXTVAL, 'bsophie', 'bs123', 'Baylee Sophie');
INSERT INTO APP_USER (ID, USERNAME, PASSWORD, FULL_NAME) VALUES (APP_USER_SEQ.NEXTVAL, 'rmarlon', 'rm123', 'Raelynn Marlon');

-- USER_FAVORITE_MOVIE
INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'bmelany'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'));

INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'bmelany'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'));

INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'bsophie'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'Aladdin'));

INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'rmarlon'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'Avengers: Endgame'));

INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'rmarlon'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'John Wick 3: Chapter 3 - Parabellum'));

INSERT INTO USER_FAVORITE_MOVIE (USER_ID, MOVIE_ID)
VALUES ((SELECT ID FROM APP_USER WHERE USERNAME = 'rmarlon'),
        (SELECT ID FROM MOVIE WHERE TITLE = 'Aladdin'));
